# Generated by Django 3.0.4 on 2020-04-11 12:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realtors',
            name='hire_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
